#!/usr/bin/env node
// Generates assets/css/tokens.css and theme.json from the approved design tokens.
// Source of truth: design-source/tokens.json (copy of 01-Design-System/tokens.json).
// Never edit the generated files by hand — change tokens.json and re-run `npm run build:tokens`.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const T = JSON.parse(readFileSync(join(root, 'design-source/tokens.json'), 'utf8'));
const theme = join(root, 'theme/techdosedaily');
const header = '/* GENERATED by tools/build-tokens.mjs from 01-Design-System/tokens.json — do not edit. */\n';

// ---------- tokens.css ----------
const colorVars = (mode) => T.color.tokens.map((t) => `  --${t.name}: ${t.value[mode]};`).join('\n');
const shadowVars = (mode) => T.shadow.tokens.map((t) => `  --${t.name}: ${t.value[mode]};`).join('\n');
const flat = ['spacing', 'radius', 'layout'].flatMap((g) => T[g].tokens).map((t) => `  --${t.name}: ${t.value};`).join('\n');
// Phase 7: metric-matched fallback faces (local Arial / Liberation Sans with size-adjust and ascent/
// descent overrides, computed from the shipped woff2 files with fontTools) sit right after each web
// font in the stack, so text laid out before the swap occupies the same space → no layout shift.
// Rendering after the swap is unchanged. Regenerate the numbers if the font files change.
const FALLBACKS = {
  Inter: [
    { weight: '400 500', local: ['Arial', 'ArialMT', 'Liberation Sans'], size: '107.48%', ascent: '90.14%', descent: '22.44%' },
    { weight: '600 700', local: ['Arial Bold', 'Arial-BoldMT', 'Liberation Sans Bold'], size: '102.35%', ascent: '94.65%', descent: '23.57%' },
  ],
  Manrope: [
    { weight: '500', local: ['Arial', 'ArialMT', 'Liberation Sans'], size: '106.14%', ascent: '100.43%', descent: '28.26%' },
    { weight: '600 800', local: ['Arial Bold', 'Arial-BoldMT', 'Liberation Sans Bold'], size: '102.29%', ascent: '104.23%', descent: '29.33%' },
  ],
};
const withFallback = (stack) => {
  const [first, ...rest] = stack.split(',').map((x) => x.trim());
  return FALLBACKS[first] ? [first, `"${first} Fallback"`, ...rest].join(', ') : stack;
};
const fallbackFaces = Object.entries(FALLBACKS).flatMap(([fam, faces]) => faces.map((f) =>
  `@font-face { font-family: "${fam} Fallback"; src: ${f.local.map((l) => `local("${l}")`).join(', ')}; font-weight: ${f.weight}; font-style: normal; size-adjust: ${f.size}; ascent-override: ${f.ascent}; descent-override: ${f.descent}; line-gap-override: 0%; }`)).join('\n');
const fams = Object.entries(T.type.families).map(([k, v]) => `  --font-${k}: ${withFallback(v)};`).join('\n');
// fonts: see theme.json fontFace below
const _faces = T.type.fonts.map((f) => `@font-face { font-family: '${f.family}'; src: url('../fonts/${f.file.split('/').pop()}') format('woff2'); font-weight: ${f.weight}; font-style: normal; font-display: swap; }`).join('\n');

const css = `${header}/* Web fonts are declared once via theme.json fontFace (front end + editor). Below: metric-matched
   local fallbacks used only until the web font arrives (font-display: swap). */
${fallbackFaces}

:root {
${colorVars('light')}
${shadowVars('light')}
${flat}
${fams}
  --gutter: 40px;
  color-scheme: light;
}
/* V1 ships light mode only. Dark values stay in tokens.json (design-system readiness) but are
   intentionally not emitted until a dark UI is designed and QA'd. */
@media (max-width: 1023px) { :root { --gutter: 32px; } }
@media (max-width: 767px)  { :root { --gutter: 20px; } }
`;
writeFileSync(join(theme, 'assets/css/tokens.css'), css);

// ---------- theme.json ----------
const px = (v) => (typeof v === 'number' ? v : parseFloat(v));
const styles = Object.fromEntries(T.type.groups.flatMap((g) => g.styles.map((s) => [s.name, { ...s, family: g.family }])));
const fontSizes = ['label', 'metadata', 'ui', 'summary', 'card-small', 'article-body', 'card-medium', 'h3', 'section-heading', 'h2', 'h1', 'display']
  .map((n) => ({ slug: n, name: n.replace(/-/g, ' ').replace(/^./, (c) => c.toUpperCase()), size: styles[n].fontSize, fluid: false }));

const fontFamilies = Object.entries(T.type.families).map(([slug, stack]) => {
  const family = stack.split(',')[0].trim();
  return {
    slug,
    name: family,
    fontFamily: withFallback(stack),
    fontFace: T.type.fonts.filter((f) => f.family === family).map((f) => ({
      fontFamily: family, fontWeight: String(f.weight), fontStyle: 'normal', fontDisplay: 'swap',
      src: [`file:./assets/fonts/${f.file.split('/').pop()}`],
    })),
  };
});

const themeJson = {
  $schema: 'https://schemas.wp.org/trunk/theme.json',
  version: 3,
  settings: {
    appearanceTools: false,
    useRootPaddingAwareAlignments: false,
    color: {
      custom: false, customDuotone: false, customGradient: false,
      defaultPalette: false, defaultGradients: false, defaultDuotone: false,
      gradients: [], duotone: [],
      palette: T.color.tokens.map((t) => ({ slug: t.name, name: t.name, color: `var(--${t.name})` })),
    },
    typography: {
      customFontSize: false, fluid: false, dropCap: false, fontStyle: false, fontWeight: false,
      letterSpacing: false, lineHeight: false, textDecoration: false, textTransform: false, writingMode: false,
      defaultFontSizes: false,
      fontFamilies,
      fontSizes,
    },
    spacing: {
      customSpacingSize: false, margin: false, padding: false, blockGap: false,
      defaultSpacingSizes: false,
      units: ['px', 'em', 'rem', '%'],
      spacingSizes: T.spacing.tokens.map((t, i) => ({ slug: String((i + 1) * 10), name: t.name, size: `var(--${t.name})` })),
    },
    border: { color: false, radius: false, style: false, width: false },
    shadow: { defaultPresets: false, presets: [] },
    dimensions: { aspectRatios: [
      { name: '16:9', slug: '16-9', ratio: '16/9' },
      { name: '4:3', slug: '4-3', ratio: '4/3' },
      { name: '1:1', slug: '1-1', ratio: '1/1' },
    ], defaultAspectRatios: false },
    layout: { contentSize: '740px', wideSize: '1280px' },
    custom: {
      radius: Object.fromEntries(T.radius.tokens.map((t) => [t.name.replace('radius-', ''), t.value])),
      container: { site: '1360px', section: '1280px', wide: '960px', content: '740px' },
    },
  },
  styles: {
    color: { background: 'var(--bg)', text: 'var(--text)' },
    typography: { fontFamily: 'var(--font-body)', fontSize: '15px', lineHeight: '1.5' },
    spacing: { blockGap: '0px', padding: { top: '0px', right: '0px', bottom: '0px', left: '0px' } },
    elements: {
      link: { color: { text: 'inherit' }, typography: { textDecoration: 'none' } },
      heading: { typography: { fontFamily: 'var(--font-display)' } },
    },
  },
  templateParts: [
    { name: 'header', title: 'Header', area: 'header' },
    { name: 'footer', title: 'Footer', area: 'footer' },
  ],
  customTemplates: [
    { name: 'page-short', title: 'Short page (no contents rail)', postTypes: ['page'] },
    { name: 'page-about', title: 'About', postTypes: ['page'] },
    { name: 'page-contact', title: 'Contact', postTypes: ['page'] },
    { name: 'page-newsletter', title: 'Newsletter', postTypes: ['page'] },
  ],
};
writeFileSync(join(theme, 'theme.json'), JSON.stringify(themeJson, null, '\t') + '\n');
console.log(`tokens.css: ${T.color.tokens.length} colours · theme.json: ${fontSizes.length} sizes, ${fontFamilies.length} families`);
