#!/usr/bin/env node
// Splits the approved bundle.css into per-template stylesheets WITHOUT changing any rule.
//
// The approved previews were rendered as fixed 390px frames, so mobile rules are scoped as
// `.tdd--m X`. In production <body> carries class "tdd", so each `.tdd--m` prefix becomes `.tdd`
// (keeping the exact specificity of the approved CSS) and the rule is wrapped in
// @media (max-width: 767px) at the SAME position in the file, preserving cascade order.
//
// Source: design-source/bundle.css (copy of 01-Design-System/bundle.css). Run `npm run build:css`.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = readFileSync(join(root, 'design-source/bundle.css'), 'utf8').split('\n');
const out = join(root, 'theme/techdosedaily/assets/css');
mkdirSync(out, { recursive: true });
const MQ = '@media (max-width: 767px)';

// Section boundaries are the "=====" banners in bundle.css (1-based line numbers resolved at runtime).
const banner = (needle) => {
  const i = src.findIndex((l) => l.includes(needle));
  if (i < 0) throw new Error(`banner not found: ${needle}`);
  // banner comment starts one line above the needle line
  return src[i - 1].startsWith('/* ====') ? i - 1 : i;
};
const B = {
  mobileCore: banner('Mobile (≤ 767px). In previews'),
  article: banner('Article (desktop). Reading column'),
  category: banner('Category page (desktop)'),
  search: banner('   Search'),
  author: banner('   Author page'),
  static: banner('   Static page system'),
  about: src.findIndex((l) => l.startsWith('/* ===== About + Contact')),
  nl404: src.findIndex((l) => l.startsWith('/* ===== Newsletter + 404')),
};
const slice = (a, b) => src.slice(a, b);
const files = {
  'core.css': [...slice(0, B.mobileCore), ...slice(B.mobileCore, B.article)],
  'article.css': slice(B.article, B.category),
  'archive.css': slice(B.category, B.search),
  'search.css': slice(B.search, B.author),
  'author.css': slice(B.author, B.static),
  'static.css': slice(B.static, B.about),
  'about-contact.css': slice(B.about, B.nl404),
  'newsletter-404.css': slice(B.nl404, src.length),
};

// Rules that live in a template section but are used site-wide move to core.css.
const SHARED = [
  /^\.tdd-crumbs/,                     // breadcrumbs: every template
  /^\.tdd-pager/, /^\.tdd--m \.tdd-pager/, // pagination: archive, search, author
  /^\.tdd-nlok/, /^\.tdd-nlsign__note/,  // newsletter states: the CTA appears site-wide
  /^\.tdd-field__err/,                  // field error text (forms)
  /^\.tdd-avatar/,                      // avatars: article byline, section desk, analysis bylines, author pages
  /^\.tdd-side-brief/,                  // Daily Tech Brief link: article and section sidebars
];

const splitSelectors = (sel) => {
  const parts = []; let depth = 0, cur = '';
  for (const ch of sel) {
    if (ch === '(') depth++;
    if (ch === ')') depth--;
    if (ch === ',' && depth === 0) { parts.push(cur.trim()); cur = ''; } else cur += ch;
  }
  if (cur.trim()) parts.push(cur.trim());
  return parts;
};

const convert = (lines) => {
  const res = []; let mq = [];
  const flush = () => { if (mq.length) { res.push(`${MQ} {`, ...mq.map((l) => '\t' + l), '}'); mq = []; } };
  for (const line of lines) {
    const m = line.match(/^([^{]+)\{(.*)\}\s*$/);
    if (!m || !line.includes('.tdd--m')) { flush(); res.push(line); continue; }
    const sels = splitSelectors(m[1]);
    const mob = sels.filter((s) => s.startsWith('.tdd--m'));
    const desk = sels.filter((s) => !s.startsWith('.tdd--m'));
    let decl = m[2].trim();
    const mobSel = mob.map((s) => s === '.tdd--m' ? '.tdd' : s.replace(/^\.tdd--m(?=[\s.:[>])/, '.tdd'));
    if (mob.includes('.tdd--m')) decl = decl.replace(/width:\s*390px;\s*/, '').replace('overflow-x: hidden', 'overflow-x: clip');
    if (desk.length) { flush(); res.push(`${desk.join(', ')} { ${m[2].trim()} }`); }
    mq.push(`${mobSel.join(', ')} { ${decl} }`);
  }
  flush();
  return res;
};

const shared = [];
const outFiles = {};
for (const [name, lines] of Object.entries(files)) {
  const keep = [];
  for (const l of lines) (name !== 'core.css' && SHARED.some((r) => r.test(l)) ? shared : keep).push(l);
  outFiles[name] = keep;
}
outFiles['core.css'].push('', '/* Shared rules moved from template sections */', ...shared);

let total = 0;
for (const [name, lines] of Object.entries(outFiles)) {
  const css = `/* GENERATED by tools/build-css.mjs from 01-Design-System/bundle.css — do not edit. */\n${convert(lines).join('\n')}\n`;
  writeFileSync(join(out, name), css);
  total += css.length;
  console.log(`${name.padEnd(20)} ${(css.length / 1024).toFixed(1)} KB`);
}
console.log(`total ${(total / 1024).toFixed(1)} KB (unminified)`);
